// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoC1TEBUD6iMq_YBEDig8dkkFvUX6hgBw',
    appId: '1:265486938993:web:59cf95579a67f40bae7cd0',
    messagingSenderId: '265486938993',
    projectId: 'parkit-acc63',
    authDomain: 'parkit-acc63.firebaseapp.com',
    storageBucket: 'parkit-acc63.appspot.com',
    measurementId: 'G-Q3Q0FZWWC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoC1TEBUD6iMq_YBEDig8dkkFvUX6hgBw',
    appId: '1:265486938993:android:2e750c9898deae4cae7cd0',
    messagingSenderId: '265486938993',
    projectId: 'parkit-acc63',
    storageBucket: 'parkit-acc63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPgKXka6MGOvP0o7gmbjyZq0Cq8QAvgtg',
    appId: '1:265486938993:ios:8d64610ac6544e95ae7cd0',
    messagingSenderId: '265486938993',
    projectId: 'parkit-acc63',
    storageBucket: 'parkit-acc63.appspot.com',
    androidClientId: '265486938993-a19u75m9mku1quv0obh52r7n45t53b23.apps.googleusercontent.com',
    iosClientId: '265486938993-irl297uc4jm37383hebnnm7n70nskk28.apps.googleusercontent.com',
    iosBundleId: 'com.nitrotechie.parkit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPgKXka6MGOvP0o7gmbjyZq0Cq8QAvgtg',
    appId: '1:265486938993:ios:8d64610ac6544e95ae7cd0',
    messagingSenderId: '265486938993',
    projectId: 'parkit-acc63',
    storageBucket: 'parkit-acc63.appspot.com',
    androidClientId: '265486938993-a19u75m9mku1quv0obh52r7n45t53b23.apps.googleusercontent.com',
    iosClientId: '265486938993-irl297uc4jm37383hebnnm7n70nskk28.apps.googleusercontent.com',
    iosBundleId: 'com.nitrotechie.parkit',
  );
}
